POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json

{
    "name": "Tom",
    "email": "tom@me.com",
    "password": "password"
}


POST http://127.0.0.1:5000/login HTTP/1.1
content-type: application/json

{
    "email": "tom@me.com",
    "password": "password"
}

GET http://127.0.0.1:5000/authTest HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJJZCI6MiwiZXhwIjoxNjE4Nzc4NjU4fQ.rT2uDxoaboaNn9CTW44T2GoRZbl3X0OY7KwYQ9cygeA
