POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json

{
    "emailaddress": "sbearman@student.vassa.edu",
    "firstname": "Sam",
    "lastname": "Bearman",
    "password": "password"
}


POST http://127.0.0.1:5000/login HTTP/1.1
content-type: application/json

{
    "email": "tom@me.com",
    "password": "password"
}

GET http://127.0.0.1:5000/classes HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJJZCI6OSwiZmlyc3RuYW1lIjoiU2FtIiwibGFzdG5hbWUiOiJCZWFybWFuIiwidXNlclR5cGUiOm51bGwsImV4cCI6MTYxOTQ4MzY3OH0.1yiK1x25aHfL2r6W7JluGORWln_imw6ftzIk-NENrGU
